### ISSUE TITLE
Sensor not registered?

### ISSUE THREAD

**Issue by arianaa30** [alejandrocq/HeartRateTest#1]
Nice start point. I was trying to play around with the heart rate data on my `Moto 360` , but your code doesn't show the values. In fact, it says: `Sensor registered: no`.

Do you know what is wrong?

**Comment by alejandrocq** [comment]
Hi @arianaa30 ! I think it may be a permissions problem. You have to grant access to sensors so the app can access them (take a look at the settings of your watch). This is an old and basic project for testing purposes, and I forgot to add the necessary code to request access to sensors to the user.

**Comment by arianaa30** [comment]
Yes, you were right. We have to manually set the permission for apps!
Thanks!

**Comment by alejandrocq** [comment]
@arianaa30 You're welcome! I'm glad that you have fixed it. I'm going to close the issue.
